packages:
  - package
#  - examples/*

catalog:
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  tsup: ^8.5.0
  tsx: ^4.20.6
  turbo: ^2.5.8
  typedoc: ^0.28.13
  typescript: 5.9.2
  vitest: ^3.2.4
